Assignment3Client/Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Assignment3Client.Attributes;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WDT_Assignment2.Models;
using Assignment3Client.ViewModels;
using System.Net.Http;
using System.Text;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Assignment3Client.Controllers
{
    [AuthorizeAdmin]
    public class AdminsController : Controller
    {

        //[Route("ioihegfi*&^797677UHFIF")]
        public async Task<IActionResult> Index()
        {
            var response = await BankAPI.InitializeClient().GetAsync("api/Customers");

            if(!response.IsSuccessStatusCode)
            {
                throw new Exception();
            }

            // Storing response details received from the web api 
            var result = response.Content.ReadAsStringAsync().Result;

            // Deserializing the response reveived from web api and storing into a list 
            var customers = JsonConvert.DeserializeObject<List<Customer>>(result);

            return View(customers);
        }

        public async Task<IActionResult> EditCustomerProfile(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var response = await BankAPI.InitializeClient().GetAsync($"api/Customers/{id}"); 

            if(!response.IsSuccessStatusCode)
            {
                throw new Exception();
            }

            var result = response.Content.ReadAsStringAsync().Result;
            var customer = JsonConvert.DeserializeObject<Customer>(result);

            ViewData["States"] = new ProfileViewModel().States;
            ViewData["Status"] = new ProfileViewModel().Status;

            return View(customer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditCustomerProfile(int id, Customer customer)
        {
            if(id != customer.CustomerID)
            {
                return NotFound();
            }

            if(ModelState.IsValid)
            {
                var content = new StringContent(JsonConvert.SerializeObject(customer), Encoding.UTF8, "application/json");
                var response = BankAPI.InitializeClient().PutAsync("api/Customers", content).Result; 

                if(response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index"); 
                } 
            }

            ViewData["States"] = new ProfileViewModel().States;
            ViewData["Status"] = new ProfileViewModel().Status;

            return View(customer);
        }

        public async Task<IActionResult> IndexToTransactions()
        {
            var response = await BankAPI.InitializeClient().GetAsync("api/Customers");
            // Storing response details received from the web api 
            var result = response.Content.ReadAsStringAsync().Result;

            // Deserializing the response reveived from web api and storing into a list 
            var customers = JsonConvert.DeserializeObject<List<Customer>>(result);

            ViewData["CustomerID"] = new SelectList(customers, "CustomerID", "CustomerID"); 

            return View();
        }

        // Trying to get transactions within specified date parameters
        public async Task<IActionResult> ViewTransactions (int id, DateTime start, DateTime end)
        {
            var startFormatted = start.ToString("dd-MM-yyyy");
            var endFormatted = end.ToString("dd-MM-yyyy");

            var response = await BankAPI.InitializeClient().GetAsync($"api/Customers/getCustomerTransactions/{id}/{startFormatted}/{endFormatted}");
           
            if (!response.IsSuccessStatusCode)
            {
                throw new Exception();
            }

            // Storing response details received from the web api 
            var result = response.Content.ReadAsStringAsync().Result;

            // Deserializing the response received from web api and storing into a list 
            var transactions = JsonConvert.DeserializeObject<List<Transaction>>(result);

            if (transactions.Count == 0)
            {
                return View("NoTransactions");
            }

            return View(transactions);
        }


       // [Route("iooihgpouisg985^%$%^$F")]
        public async Task<IActionResult> ViewBillPays(int id)

        {
            var response = await BankAPI.InitializeClient().GetAsync($"api/Customers/getCustomerBillPays/{id}");

            if(!response.IsSuccessStatusCode)
            {
                throw new Exception();
            }

            // Storing response details received from the web api 
            var result = response.Content.ReadAsStringAsync().Result;

            // Deserializing the response received from web api and storing into a list 
            var billPays = JsonConvert.DeserializeObject<List<BillPay>>(result);

            return View(billPays);
        }


        public async Task<IActionResult> EditBillPay(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var response = await BankAPI.InitializeClient().GetAsync($"api/BillPays/{id}");

            if (!response.IsSuccessStatusCode)
            {
                throw new Exception();
            }

            var result = response.Content.ReadAsStringAsync().Result;
            var billpay = JsonConvert.DeserializeObject<BillPay>(result);

            ViewData["Status"] = new BillPayViewModel().Status;

            return View(billpay);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditBillPay(int id, BillPay billpay)
        {

            if (id != billpay.BillPayID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                var content = new StringContent(JsonConvert.SerializeObject(billpay), Encoding.UTF8, "application/json");
                var response = BankAPI.InitializeClient().PutAsync("api/BillPays", content).Result;

                // These are to get customerID so it can be passed to ViewBillPays and get back into that page
                var response2 = BankAPI.InitializeClient().GetAsync($"api/Customers/getCustomerFromBillPay/{id}");
                int customerID = int.Parse(response2.Result.Content.ReadAsStringAsync().Result);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("ViewBillPays", new { id = customerID });
                }
            }
            ViewData["Status"] = new BillPayViewModel().Status;

            return View(billpay);
        }

        
        public async Task<IActionResult> Charts(int id, DateTime start, DateTime end)
        {
            var startFormatted = start.ToString("dd-MM-yyyy");
            var endFormatted = end.ToString("dd-MM-yyyy");

            var response = await BankAPI.InitializeClient().GetAsync($"api/Customers/getChartData/{id}/{startFormatted}/{endFormatted}");

            if (!response.IsSuccessStatusCode)
            {
                throw new Exception();
                //return View("NoTransactions");
            }

            // Storing response details received from the web api 
            var result = response.Content.ReadAsStringAsync().Result;

            // Deserializing the response received from web api and storing into a list 
            var transactions = JsonConvert.DeserializeObject<List<object>>(result);

            if (transactions.Count == 0)
            {
                return View("NoTransactions");
            }

            ViewBag.id = id;
            ViewBag.start = startFormatted;
            ViewBag.end = endFormatted;

            return View();
        }


        //public async Task<IActionResult> Charts2(int id, DateTime start, DateTime end)
        //{
        //    var startFormatted = start.ToString("dd-MM-yyyy");
        //    var endFormatted = end.ToString("dd-MM-yyyy");

        //    var response = await BankAPI.InitializeClient().GetAsync($"api/Customers/getChart2Data/{id}/{startFormatted}/{endFormatted}");

        //    if (response == null)
        //    {
        //        return View("NoTransactions");
        //    }

        //    if (!response.IsSuccessStatusCode)
        //    {
        //        throw new Exception();
        //    }

        //    return View();
        //}

        //public async Task<IActionResult> Charts3(int id, DateTime start, DateTime end)
        //{
        //    var startFormatted = start.ToString("dd-MM-yyyy");
        //    var endFormatted = end.ToString("dd-MM-yyyy");

        //    var response = await BankAPI.InitializeClient().GetAsync($"api/Customers/getChart2Data/{id}/{startFormatted}/{endFormatted}");

        //    if (response == null)
        //    {
        //        return View("NoTransactions");
        //    }

        //    if (!response.IsSuccessStatusCode)
        //    {
        //        throw new Exception();
        //    }

        //    return View();
        //}
    }
}

Assignment3Client/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NWBA Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                @{
                    // Boolean - if Session object contains name of customer, means it is logged in
                    var isLoggedIn = Context.Session.GetInt32(nameof(AdminLogin.AdminLoginID)).HasValue;
                }


                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                    <ul class="navbar-nav">


                        <!-- If admin is logged, fetch session to display the name of customer -->
                        @if (isLoggedIn)
                        {

                            <li class="nav-item">
                                <!-- NOTE: NEED TO CREATE LOGOUT FUNCTION-->
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Logout">Logout</a>
                            </li>
                        }

                    </ul>


                    <ul class="navbar-nav flex-grow-1">

                        @if (isLoggedIn)

                        {
                            <i class="fas fa-users-cog"></i>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admins" asp-action="Index">NWBA Admin | Grow Your Livelihood</a>
                            </li>
                        }
                        else
                        {
                            <i class="fas fa-users-cog"></i>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">NWBA Admin | Grow Your Livelihood</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Assignment3Client - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/3456e330ee.js" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>